apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: flask
        image: 876178095025.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 5000

